MATCH (n:Drug) RETURN n.schemaClass;
MATCH (n:ProteinDrug) RETURN n.schemaClass;
MATCH (n:Drug:ProteinDrug) RETURN n.schemaClass;
MATCH (n:Taxon)-->(m:Species) RETURN n.schemaClass, m.schemaClass;
MATCH (n)-->(m:Interaction)-->(o) RETURN n.schemaClass, m.schemaClass, o.schemaClass;
MATCH (n{displayName:"Autophagy"}) RETURN n.schemaClass;
MATCH (n{displayName:"Autophagy"})-->(m) RETURN m.schemaClass;
MATCH (n{displayName:"Autophagy"})-->(m)-->(p) RETURN p.schemaClass;
MATCH (n{displayName:"Autophagy"})-->(m)-->(p)-->(q) RETURN q.schemaClass;
MATCH (n{displayName:"Autophagy"})-->(m)-->(p)-->(q)-->(r) RETURN r.schemaClass;
MATCH (n{displayName:"Autophagy"})-->(m)-->(p)-->(q)-->(r)-->(s) RETURN s.schemaClass;
MATCH (n{displayName:"Autophagy"})-->(m)-->(p)-->(q)-->(r)-->(s)-->(t) RETURN t.schemaClass;
MATCH (n{displayName:"Autophagy"})-->(m)-->(p)-->(q)-->(r)-->(s)-->(t)-->(v) RETURN v.schemaClass;
MATCH (n{displayName:"APOE-4 [extracellular region]"}) RETURN n.schemaClass;
MATCH (n{displayName:"APOE-4 [extracellular region]"})-->(m) RETURN m.schemaClass;
MATCH (n{displayName:"APOE-4 [extracellular region]"})-->(m)-->(p) RETURN p.schemaClass;
MATCH (n{displayName:"APOE-4 [extracellular region]"})-->(m)-->(p)-->(q) RETURN q.schemaClass;
MATCH (n{displayName:"APOE-4 [extracellular region]"})-->(m)-->(p)-->(q)-->(r) RETURN r.schemaClass;
MATCH (n{displayName:"APOE-4 [extracellular region]"})-->(m)-->(p)-->(q)-->(r)-->(s) RETURN s.schemaClass;
MATCH (n{displayName:"APOE-4 [extracellular region]"})-->(m)-->(p)-->(q)-->(r)-->(s)-->(t) RETURN t.schemaClass;
MATCH (n{displayName:"APOE-4 [extracellular region]"})-->(m)-->(p)-->(q)-->(r)-->(s)-->(t)-->(v) RETURN v.schemaClass;
MATCH (n)-[e:release]->(m) RETURN n.schemaClass, m.schemaClass;
MATCH (n)-[e:interactor]->(m) RETURN n.schemaClass, m.schemaClass;
MATCH (n)-[e:surroundedBy]->(m) RETURN n.schemaClass, m.schemaClass;
MATCH (n)-[:hasEvent]->(m) RETURN n.schemaClass, m.schemaClass;
MATCH (n:Pathway)-[:hasEvent]->(m:ReactionLikeEvent) RETURN n.schemaClass, m.schemaClass;
MATCH (r:ReactionLikeEvent)-[:output]->(s:PhysicalEntity) RETURN r.schemaClass, s.schemaClass;
MATCH (n:DatabaseObject{isChimeric:false}) RETURN n.schemaClass;
MATCH (n:DatabaseObject{isChimeric:true}) RETURN n.schemaClass;
MATCH (b)-->(a:Pathway) RETURN a.schemaClass;
MATCH (c)-->(b)-->(a:Pathway) RETURN a.schemaClass, c.schemaClass;
MATCH (c)-->(b)-->(a:Pathway) RETURN b.schemaClass;
MATCH (c)-->(b)-->(a:Pathway) RETURN c.schemaClass;
MATCH (c)-->(b)-->(a:Pathway) RETURN a.schemaClass;
